language: python
sudo: false

env:
  - LUA="lua=5.3"
  - TEST_DIR=hello-world
  - TEST_DIR=hamming
  - TEST_DIR=resistor-color-trio

before_install:
  - pip install hererocks
  - hererocks lua_install -r^ --$LUA
  - export PATH=$PATH:$PWD/lua_install/bin # Add directory with all installed binaries to PATH

install:
  - luarocks install busted
  - luarocks install luacov
  - luarocks install luacov-coveralls

script:
  - cd $TEST_DIR &&  busted

after_success:
  - luacov-coveralls --exclude $TRAVIS_BUILD_DIR/lua_install
