language: python
sudo: false

env:
  - LUA="lua=5.3"

before_install:
  - pip install hererocks
  - hererocks lua_install -r^ --$LUA
  - export PATH=$PATH:$PWD/lua_install/bin # Add directory with all installed binaries to PATH

install:
  - luarocks install busted
  - luarocks install luacov
  - luarocks install luacov-coveralls

script:
  - cd exercism_lua && for dir in $(find -maxdepth 1 -type d -not -path './\.*'); do pushd $dir; busted || exit; popd; done

after_success:
  - luacov-coveralls --exclude $TRAVIS_BUILD_DIR/lua_install
